#!/bin/bash



>file
>listeRouge


dpkg --status > file



while read ligne
do
   
    if [[ $ligne == 'Package: '* ]];then 
        a=3  
       
    fi
    
    if [[ $a == 3 ]]; then  
        IFS=': '
        set $ligne
        IFS=$svIFS;
        nomPa=$2
        let a--
        else if [[ $a == 2 ]]; then
            let a--
            else if [[ $a == 1 && $ligne == *'important'* ]]; then
                echo $nomPa >> listeRouge
                let a--
            fi
        fi
    fi
    
    

done < file

rm file

