#!/bin/bash

#--------------------------------------------
# permet de configurer SeReC pour un nouveau type d'utilisateur
#--------------------------------------------

#On récupère le chemin de serec.config
cheminSerec='/etc/SeReC/serec.config'

#On demande de saisir le nom de l'utilisateur pour lequel on veut installer serec
echo "Veuillez saisir l'utilisateur : "
read nom

# On demande le type de profil de l'utilisateur
echo ""
echo "=== CHOIX DU PROFIL ==="
echo "1) Administrateur"
echo "2) Secrétaire"
echo "3) Gamer"
echo "4) Mathématicien"
echo "5) Ingénieur Audiovisuel"

numListe=-1

while (($numListe == -1))
do 
    echo -n "Saisir le numéro du profil souhaité : ";
    read numListe
    
    case $numListe in
        1) 
        sed -i '7d' $cheminSerec
        sed -i "7i\Administrateur : 1\t" $cheminSerec
        ;;
        2) 
        sed -i '8d' $cheminSerec
        sed -i "8i\Secretaire : 1\t" $cheminSerec
        ;;
        3) 
        sed -i '9d' $cheminSerec
        sed -i "9i\Gamer : 1\t" $cheminSerec
        ;;
        4)
        sed -i '10d' $cheminSerec
        sed -i "10i\Mathematicien : 1\t" $cheminSerec
        ;;
        5) 
        sed -i '11d' $cheminSerec
        sed -i "11i\Ingenieur Audio-Visuel : 1\t" $cheminSerec
        ;;
        *) echo "Erreur, veuillez choisir un chiffre entre 1 et 5"
           numListe=-1;;
    esac
done
