#!/bin/bash

#On récupère le chemin de serec.config
#TODO mettre le chemin definitif
cheminSerec='/usr/bin/serec.config'


#On recupere le chemin des scripts
#TODO mettre le chemin definitif
chemin='/usr/bin'

#On ecrit la fonction command_not_found_handle si elle n'existe pas déjà
cat /etc/bash.bashrc > bashrc
dejaEcrit=0
while read ligne
do
    if [[ $ligne == "command_not_found_handle() {" ]]
    then
        dejaEcrit=1
    fi
done < bashrc

if [ $dejaEcrit -eq "0" ]
then
echo -e "command_not_found_handle() {\n    $chemin/SeReC/client.exe \"\$1\";\n    if [ -e /usr/bin/\"\$1\" ]\n    then\n        \"\$1\";\n    else\n        echo \"commande introuvable\";\n    fi\n    return 127;\n}" | sudo tee -a /etc/bash.bashrc
fi
rm bashrc




# On ajoute au PATH le chemin où sont stockée les listes pour pouvoir executées
# les listes n'importe où dans la console
var=$(sed -n '2p' $cheminSerec)
cheminListe=${var##* }

#On ajoute la ligne si elle n'est pas déjà ecrite
cat /home/$nom/.bashrc > lebashrc
dejaEcrit=0
while read ligne
do
    if [[ $ligne == "export PATH=\"\$PATH:$cheminListe\"" ]]
    then
        dejaEcrit=1
    fi
done < lebashrc

if [ $dejaEcrit -eq "0" ]
then
    echo "export PATH=\"\$PATH:$cheminListe\"" >> /home/$nom/.bashrc
fi
rm lebashrc



# ajout du lancement des serveurs au démarrage 
#TODO changer les chemins des serveurs quand on aura les chemins définitifs

> /etc/rc.local
echo -e "#!/bin/sh -e\n#\n# rc.local\n#\n# This script is executed at the end of each multiuser runlevel.\n# Make sure that the script will "exit 0" on success or any other\n# value on error.\n#\n# In order to enable or disable this script just change the execution\n# bits.\n#\n# By default this script does nothing.\n/usr/bin/SeReC/serveur.exe > /dev/null 2&1 &\n/usr/bin/SeReC/serveurDesinstallation.exe > /dev/null 2&1 &\nexit 0" | sudo tee -a /etc/rc.local

chmod +x /etc/rc.local


echo "=== Installation terminé ==="
