#!/bin/bash

var=$(sed -n '3p' /home/romain/Documents/ProjetS4/ProjetS3S4-Allo-memoire/src/serec.config)
chemin=${var##* }
Ladate=$(date)
echo -e \\n$Ladate \\n >>$chemin/LogInstallation.log
apt -y --purge autoremove $1 2>/dev/null >>$chemin/LogInstallation.log


