#!/bin/bash

echo "Tentative d'installation de $1"

var=$(sed -n '3p' /home/romain/Documents/ProjetS3/serec.config)
chemin=${var##* }
Ladate=$(date)
echo -e \\n$Ladate \\n >>$chemin/LogInstallation.log
apt-get  install -y $1 2>/dev/null >>$chemin/LogInstallation.log
